### ISSUE TITLE
Дата выхода расширения

### ISSUE THREAD

**Issue by Gordon-Freeman-hev** [phpbbmodders/trackers#1]
Когда выйдет данное расширение?

**Comment by rmcgirr83** [comment]
Uhmmm, try English please.

**Comment by Gordon-Freeman-hev** [comment]
Я не знаю английского языка.

**Comment by rmcgirr83** [comment]
Then use google translate.  I don't know Russian but took the initiative to translate.

**Comment by Gordon-Freeman-hev** [comment]
Я не знаю английского языка.
Не зная английского языка я не могу проверить адекватность перевода.

**Comment by bonelifer** [comment]
Currently unlikely.
